### PR TITLE
Proposal: Provisions for Enslavement Cases

### PR DESCRIPTION
**Pull request by stoicflame**
The attached changes constitute enhancements to the spec to account for enslavement cases. Please refer to the [group e-mail discussion](https://groups.google.com/d/topic/gedcomx/lxUQXkR3Qjo/discussion) for context.

Comments are welcome.

## Known Fact Types: Additions

URI | description
----|-------------
`http://gedcomx.org/Enslavement`| A fact of the enslavement of a person.
`http://gedcomx.org/RouteToFreedom`| A fact of the emancipation, manumission, escape or other route to freedom of a person who was previously enslaved.

## Known Relationship Types: Additions

URI | description
----|-------------
`http://gedcomx.org/EnslavedBy`| A relationship from an enslaved person to the enslaver or slaveholder of the person.

## Known Fact Qualifiers: Additions

name | value
-----|-------
`http://gedcomx.org/Transport`| The name of the transport associated with an event that indicates a move.
`http://gedcomx.org/NonConsensual`| An indicator that the event occurred non-consensually, e.g. under enslavement.

### CODE REVIEW

**Comment by nractive** [comment]
Additions for cases of enslavement are certainly welcomed. I assume that these are supported by the `Group` and `GroupRole` data types (as possibly modified per discussions in Proposal: Group #321). Otherwise, these additions would be insufficient by themselves.

Regarding these new additions, some things puzzle me. I am having to do some mental contortions to try to fit my real-life example into pseudo-code using these additions. Here is a modified partial section of @stoicflame's earlier code:

```yaml
Person:
  name: Juliet
  gender: Female
  facts:
    birth:
      date: 1834
    death:
      date: 1867
    emancipation: # A fact of the emancipation, manumission, escape or other route to freedom of a person who was previously enslaved.
      date: 1865

Person:
  name: Simon
  gender: Male
  facts:
    birth:
      date: 1853
    death:
      date: 1924
    emancipation: #A fact of the emancipation, manumission, escape or other route to freedom of a person who was previously enslaved.
      date: 1865

Person:
  name: Malinda
  facts:
    Enslavement: #A fact of the enslavement of a person.
    birth:
      date: 1798
    death:
      date: 1874

Person:
  name: Frank
  gender: Male
  facts:
    birth:
      date: 1820
    death:
      date: 1898
    occupation: "Overseer"
    
Person:
  name: Henry
  
Person:
  name: Sarah

Relationship:
  type: EnslavedBy: #A relationship from an enslaved person to the enslaver or slaveholder of the person.
  person1: Juliet
  person2: Malinda
  facts:
    Non-Consensual: #An indicator that the event occurred non-consensually, e.g. under enslavement.
    begin:
      date: 1834
    end:
      date: 1865

Relationship:
  type: ParentChild
  person1: Juliet
  person2: Simon
  facts:
    Biological

Relationship:
  type: ParentChild
  person1: Frank
  person2: Simon
  facts:
    Biological
      sources: (DNA evidence, etc.)

Relationship:
  type: Couple
  person1: Frank
  person2: Juliet
  facts:
    Non-Consensual: #An indicator that the event occurred non-consensually, e.g. under enslavement.

Group:
  name: "Enslaved Population on Malinda Farm"
  date: 1830 - 1865
  role:
    person: Malinda
    details: "Slaveholder"
  role:
    person: Frank
    details: "Overseer"
  role:
    person: Juliet
    details: "Enslaved"
  role:
    person: Simon
    details: "Enslaved"
```


This might work, but it is not easy to follow. It just doesn't seem straightforward or complete.

A two-way relationship is implied with the EnslavedBy fact, but it can easily be confusing as to which, person1 or person2, is the slaveholder and which is the slave. Moreover, “EnslavedBy” to me is a one-sided reference (to the slaveholder) and not a term I would describe for a relationship.

“Emancipation” will likely not be interpreted to include other methods of reaching freedom. There needs to be a better term that is inclusive and still representative of the description. (I’ll seek suggestions from others.)

Great work so far, and very much appreciated.

**Comment by stoicflame** [comment]
> I assume that these are supported by the Group and GroupRole data types. 

Yes.

> A two-way relationship is implied with the EnslavedBy fact, but it can easily be confusing as to which, person1 or person2, is the slaveholder and which is the slave. 

Perhaps a missing piece of information is the part of the current spec that explicitly states directionality? See the note at the end of the description of [Section 2.2](https://github.com/FamilySearch/gedcomx/blob/master/specifications/conceptual-model-specification.md#22-the-relationship-data-type): "Note: when a relationship type implies direction, the relationship is said to be from person1 to person2."

> “Emancipation” will likely not be interpreted to include other methods of reaching freedom.

I'm fine with `RouteToFreedom` if it's important. I just wish we could think of a more general term that also implies that a date and a place should be included too.

**Comment by stoicflame** [comment]
Still looking for some more comments/feedback on this thread.

At 874bac65 I renamed `Emancipation` to `RouteToFreedom` as recommended by expert opinion above.

**Comment by nractive** [comment]
There is discussion going on about this in a Facebook group. Please hold temporarily. I'll be back when I hear a consensus.

**Comment by nractive** [comment]
After several calls for input on this issue and receiving much comment, I find that there is no consensus on how to best tag a fact of achieving freedom for an enslaved person. `RouteToFreedom` some say is thought of in context to the Underground Railroad. `Emancipation` is thought of in only one context and not inclusive of manumission, escape, or other ways to gain freedom. No single word works well.

I heard no objection to the dropping of `RouteToFreedom` as a fact type as long as `Enslavement`, `EnslavedBy`, and `NonConsensual` are retained. That, therefore, is the recommendation.

I guessed wrong in thinking `RouteToFreedom` or similar would be highly desired. It does not relate directly to relationships, so perhaps not essential.  Genealogists will still be able to include notations to a record if desired.

There are cheers from many for the other tags that will enable genealogists and family historians to make new connections. Thanks!

**Comment by stoicflame** [comment]
@nractive thank you so much for your work in this regard.

At fb636ce2 I have removed `RouteToFreedom` from the proposal. I think it makes since that for now we could just have an end date on the `Enslavement` fact.

I'll let the proposal sit for another week or two in case anybody else has any comments. Then I'll merge and close the proposal, making it an official part of the spec.

**Comment by stoicflame** [comment]
This issue has been merged and is now an official part of the spec.

**Pull request merged**
