### PR TITLE
Adding a fact type for civil award

### PR DESCRIPTION
**Pull request by vbrossier**
It can be usefull for a person that have a civil medal or decoration.

### CODE REVIEW

**Comment by stoicflame** [comment]
Nice. Seems like a good way to capture and distinguish from a `MilitaryAward`, yes?

**Comment by vbrossier** [comment]
Yes exactly. Some medals are not military. And they are not related to studies either (http://gedcomx.org/Education)

**Comment by pirtleshell** [comment]
Has there ever been discussion around a more general `Award` fact type with a `type` or `category` field that could be used to distinguish from Military, Civil, or some other kind?

It seems like an unnecessary complication to have different fact types for different sorts of awards that will inevitably have similar fields. Beyond increased flexibility, an `Award` fact type would also prevent the need to add a fact type for every newly conceived award type in the future.

I understand something like that (removing `MilitaryAward`) would not be backwards-compatible with the current fact type list. In that case, I guess I'm just questioning the "Civil" word choice. Is a soccer trophy a "civil" award? A Nobel Prize? What about winning the lottery?

**Comment by stoicflame** [comment]
> Has there ever been discussion around a more general Award fact type with a type or category field that could be used to distinguish from Military, Civil, or some other kind?

There's already a `Qualifier` on `Fact` that could be used to "qualify" the award (e.g. as a civil award). But assuming we keep `MilitaryAward` for backwards compatibility, what other qualifiers would there be other than `Civil`?

**Comment by thomast73** [comment]
So...I was trying to answer this question for myself.  I could think of religious/ecclesiastical as another category.  I could think of honors bestowed by a sovereign (I was thinking about knighthood...but cannot find an example of what I was remembering).  So...then I found this page...and it will get you thinking about how vast "award" is as a category.  It mentions a number of categories...and links to a number of other pages...that link to other pages.  You get the point.  https://en.wikipedia.org/wiki/List_of_awards

**Comment by stoicflame** [comment]
@vbrossier what do you think about defining this type more generically (e.g. `Award`) and defining a list of qualifiers for the award type (including `Civil`)?

**Comment by vbrossier** [comment]
@stoicflame Yes, it seems to be a good solution !

**Comment by vbrossier** [comment]
I have made a new commit on my pull request to change that

**Pull request merged**
